---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-merge-conflict
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-xml
          - id: check-added-large-files
          - id: check-ast

    - repo: https://github.com/codespell-project/codespell
      rev: v2.2.6
      hooks:
          - id: codespell
            name: codespell
            description: Checks for common misspellings in text files.
            entry: codespell  *
            language: python
            types: [text]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
            files: ^.github|./\.yaml

    - repo: https://github.com/psf/black
      rev: 23.10.0
      hooks:
        - id: black
          args: ["--line-length=99", "--preview"]

    - repo: https://github.com/PyCQA/flake8
      rev: 6.1.0
      hooks:
        - id: flake8
          args: ["--ignore=E501,W503,E203"] # ignore too long line and line break before binary operator,

    - repo: local
      hooks:
      - id: ament_lint_cmake
        name: ament_lint_cmake
        description: Check format of CMakeLists.txt files.
        entry: ament_lint_cmake
        language: system
        files: CMakeLists\.txt$

    - repo: https://github.com/PyCQA/doc8
      rev: v1.1.1
      hooks:
        - id: doc8
          args: ['--max-line-length=100', '--ignore=D001']
          exclude: ^.*\/CHANGELOG\.rst/.*$

    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: v14.0.6
      hooks:
        - id: clang-format
